dist: trusty #bionic
sudo: true
language: cpp
branches: 
  only:
    - testing
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "gcc-6"
      - "g++-6"
      - "python3"
      - "python3-pip"
      - "cmake-data"
      - "cmake"
      - "lcov"
    
before_script:
  - "pip3 install --user cpp-coveralls"
    # - "./configure --enable-gconv && make && make check"
  # next 4 lines are for mkl
  - "wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB"
  - "sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB"
  - "sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'"
  - "sudo apt-get -y update"
  - "sudo apt-get install -y intel-mkl-2019.0-045"
cache:
  directories:
    /opt/intel

script:
  - "./build-cpu 2"

after_script:

after_success:
  - "coveralls --exclude lib --exclude tests --gcov-options '\-lp'a"
  # Creating report
  #- cd ${TRAVIS_BUILD_DIR}
  #- lcov --directory . --capture --output-file coverage.info # capture coverage info
  #- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  #- lcov --list coverage.info #debug info
  ## Uploading report to CodeCov
  #- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email: true

