dist: trusty #bionic
sudo: true
language: cpp
branches: 
  only:
    - testing
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "gcc-6"
      - "g++-6"
      - "python3"
      - "python3-pip"
      - "cmake"
    
before_script:
  - "pip3 install --user cpp-coveralls"
  # next 4 lines are for mkl
  - "wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB"
  - "sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB"
  - "sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'"
  - "sudo apt install intel-mkl-2019.0-045"


script:
  - "./build-cpu 2"
after_script:

