dist: trusty #bionic
sudo: false
language: cpp
branches: 
  only:
    - testing
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
    
before_script:
  - "pip3 install --user cpp-coveralls"
script:
  - ./build-cpu
after_script:

